// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbvjbumlbjxmmrwoosvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidmpidW1sYmp4bW1yd29vc3ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTQ5MDUsImV4cCI6MjA2MjQzMDkwNX0.L06KpjBU142jzEkXL5oxWoDNLwPwC1_1XYr6WxpKgBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);